import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Project Finance — Infrastructure Debt, SPVs & Financial Close",
  description:
    "A comprehensive guide to project finance: how SPVs work, lender due diligence, debt structuring, risk allocation, and bringing infrastructure projects to financial close.",
  alternates: { canonical: "/project-finance/project-finance" },
  openGraph: {
    title: "Project Finance Guide — Oghie Blog",
    description:
      "How infrastructure projects are financed through SPVs, non-recourse debt, and multi-party risk allocation frameworks.",
    url: "/project-finance/project-finance",
    type: "article",
  },
};

const SERIF = "var(--font-display), 'Libre Baskerville', Georgia, serif";
const BODY  = "var(--font-body), Georgia, 'Times New Roman', serif";
const SANS  = "var(--font-sans), system-ui, sans-serif";

const SECTIONS = [
  {
    heading: "What Is Project Finance?",
    body: `Project finance is a specialist lending and investment technique used to fund large, capital-intensive assets — power plants, toll roads, pipelines, hospitals, LNG terminals, airports — where the debt is repaid exclusively from the revenues generated by that specific asset rather than from the broader balance sheet of the sponsoring company.\n\nThis "non-recourse" or "limited recourse" structure is the defining characteristic. Lenders have no claim on the sponsor's other assets if the project fails. Instead, they take security over the project itself — its contracts, revenues, accounts, and physical assets — and they rely on exhaustive contractual risk allocation and cash flow modelling to satisfy themselves that the project can service its debt under a range of stress scenarios.\n\nProject finance originated in the oil and gas sector in the 1970s but now underpins the financing of the world's critical infrastructure, with global deal volumes exceeding $300 billion per year.`,
  },
  {
    heading: "The Special Purpose Vehicle (SPV)",
    body: `Every project finance deal is structured through a Special Purpose Vehicle — a legally ring-fenced entity created solely to develop, own, and operate the specific project. The SPV has no assets or liabilities beyond the project itself, which is what enables the non-recourse financing structure.\n\nSponsors (the equity investors) capitalise the SPV with equity and then raise the project debt at the SPV level. From a lender's perspective, all cash flows flow into and out of the SPV under tightly controlled conditions. Excess cash above a required minimum balance (the debt service reserve account) is typically trapped until financial covenants are met, then swept to equity as dividends.\n\nThe clean separation between the project and the sponsor creates accounting benefits — off-balance-sheet treatment under certain standards — and limits contagion risk between project failure and the sponsor's corporate credit rating.`,
  },
  {
    heading: "Key Parties & Their Roles",
    body: `Project finance transactions involve a constellation of parties. Sponsors provide the equity, develop the project concept, and manage construction and operations. Lenders — commercial banks, development finance institutions (DFIs), export credit agencies (ECAs), and institutional investors in the bond market — provide the debt.\n\nThe offtaker purchases the project's output (power, gas, water) under a long-term contract and is often the most critical credit in the entire structure. Without a creditworthy offtaker, most projects cannot achieve bankability. The EPC (Engineering, Procurement, and Construction) contractor builds the project under a fixed-price, date-certain contract that transfers construction risk away from lenders. The O&M (Operations & Maintenance) contractor runs the asset post-completion.\n\nGovernments and regulatory bodies grant concession agreements and permits — without which there is no project — and are often themselves offtakers or guarantors, particularly in emerging markets where private sector creditworthiness is limited.`,
  },
  {
    heading: "Risk Allocation — The Foundation of Bankability",
    body: `Project finance is fundamentally a risk allocation exercise. Lenders will fund a project only if every material risk is either mitigated, transferred to a creditworthy party, or accepted by the equity (sponsors). The project's suite of contracts — the offtake agreement, EPC contract, O&M contract, fuel supply agreement, concession — together form the contractual framework that allocates risk.\n\nConstruction risk (cost overruns and delays) is typically borne by the EPC contractor through the fixed-price, turnkey contract. Technology risk — the risk that unproven technology underperforms — is mitigated by using proven equipment with performance guarantees and liquidated damages provisions. Revenue risk — the risk that revenues fall short — is mitigated by long-term offtake or power purchase agreements (PPAs) with creditworthy counterparties.\n\nCurrency and interest rate risk can be hedged through derivatives. Political risk in emerging markets is often mitigated through political risk insurance from DFIs and ECAs, or through investment treaties. The residual risk — the "equity cushion" — is what sponsors accept in exchange for the equity returns.`,
  },
  {
    heading: "Debt Structuring & Financial Close",
    body: `Project debt is typically structured in layers. Senior debt — the largest and cheapest tranche — is secured against all project assets and has first claim on cash flows. Subordinated debt (mezzanine) sits below senior debt and commands higher interest rates. In some transactions, institutional investors provide long-dated bonds (project bonds) rather than bank loans, particularly in stable, investment-grade markets.\n\nThe key financial metrics that lenders underwrite are the Debt Service Coverage Ratio (DSCR) — the ratio of available cash flow to scheduled debt service — and the Loan Life Coverage Ratio (LLCR), which looks at coverage over the full loan life. Minimum DSCR covenants of 1.20–1.35× are typical; breach triggers cash trap mechanisms and ultimately default.\n\nFinancial close is the milestone at which all project agreements are executed, all conditions precedent (CPs) are satisfied, and lenders fund the first drawdown. Reaching financial close on a large infrastructure project can take two to five years of development effort and cost tens of millions of dollars in advisor fees — a sobering reminder of why project development risk is real and significant.`,
  },
  {
    heading: "Lender Due Diligence",
    body: `Lenders in project finance transactions conduct exhaustive due diligence before committing capital. Technical due diligence — conducted by independent engineers appointed by the lenders (the Lender's Independent Engineer or LIE) — assesses the technical feasibility of the project, the adequacy of the EPC contract, and the reasonableness of the construction timeline and cost estimate.\n\nFinancial model due diligence involves lenders' financial advisors interrogating every assumption in the sponsor's financial model — revenue projections, cost escalation, inflation assumptions, debt sizing — and running independent stress tests and sensitivity analyses. The model must demonstrate that the project can service its debt even under downside scenarios.\n\nLegal due diligence covers the entire contractual framework: are the contracts bankable? Do they adequately allocate risk? Are the offtaker covenants strong enough? Is the concession agreement enforceable in the relevant jurisdiction? Environmental and social due diligence — aligned with IFC Performance Standards — is now a prerequisite for multilateral and many commercial lenders.`,
  },
  {
    heading: "Project Finance in Emerging Markets",
    body: `Emerging markets present both the greatest need for infrastructure investment — the infrastructure funding gap in developing countries runs to trillions of dollars annually — and the most complex risk environment. Weak institutional frameworks, currency volatility, political uncertainty, and shallow local capital markets all complicate the financing of projects.\n\nDevelopment Finance Institutions (DFIs) — the World Bank Group's IFC, the African Development Bank, the Asian Development Bank, and bilateral DFIs like Britain's BII and America's DFC — play a catalytic role. Their participation signals government commitment, provides political risk mitigation, and mobilises private capital that would otherwise not flow to the transaction.\n\nBlended finance structures — combining concessional capital from DFIs with commercial capital — have emerged as the dominant mechanism for making difficult projects in fragile states bankable. The DFI takes the first-loss position, enabling commercial lenders to participate at acceptable risk-adjusted returns.`,
  },
  {
    heading: "Renewable Energy & The Energy Transition",
    body: `Project finance has become the financing structure of choice for the global energy transition. Solar, wind, and battery storage projects are natural fits: they have predictable, low-volatility operating costs (no fuel), long asset lives, and revenues that are easily contracted through PPAs with utilities or governments.\n\nThe rapid commoditisation of renewable energy technology — solar module costs have fallen 90% since 2010 — has driven PPA prices to historic lows, tightening equity returns and putting pressure on deal teams to optimise capital structures. Merchant risk — selling power at market prices without a fixed offtake contract — has become more common as projects compete to offer the cheapest power, but it introduces revenue volatility that changes the lender conversation fundamentally.\n\nGreen bonds and sustainability-linked debt instruments have opened new pools of capital for eligible projects. The alignment between climate commitments and the scale of capital needed for the energy transition means that project finance professionals are now at the front line of one of the most consequential investment challenges of the century.`,
  },
];

export default function ProjectFinancePage() {
  return (
    <>
      {/* ── Header ───────────────────────────────────────── */}
      <div
        style={{
          backgroundColor: "var(--color-navy-900)",
          paddingTop: "3.5rem",
          paddingBottom: "3.5rem",
          borderBottom: "3px solid var(--color-gold-500)",
        }}
      >
        <div className="container-blog">
          <Link
            href="/project-finance"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "0.375rem",
              fontSize: "0.875rem",
              color: "var(--color-navy-400)",
              textDecoration: "none",
              marginBottom: "1.5rem",
            }}
            className="hover:text-white"
          >
            <ArrowLeft size={14} /> Project Finance
          </Link>

          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: "0.75rem",
              marginBottom: "0.875rem",
            }}
          >
            <div
              style={{
                width: "3px",
                height: "24px",
                backgroundColor: "var(--color-gold-500)",
                borderRadius: "1px",
              }}
            />
            <span
              style={{
                fontSize: "0.6875rem",
                fontWeight: 700,
                letterSpacing: "0.14em",
                textTransform: "uppercase",
                color: "var(--color-gold-500)",
                fontFamily: SANS,
              }}
            >
              Project Finance
            </span>
          </div>

          <h1
            style={{
              fontFamily: SERIF,
              fontSize: "clamp(2rem, 5vw, 3rem)",
              fontWeight: 900,
              color: "#ffffff",
              lineHeight: 1.1,
              letterSpacing: "-0.02em",
              marginBottom: "0.875rem",
            }}
          >
            Project Finance
          </h1>
          <p
            style={{
              fontFamily: BODY,
              fontSize: "1.0625rem",
              fontStyle: "italic",
              color: "var(--color-navy-400)",
              maxWidth: "68ch",
              lineHeight: 1.65,
            }}
          >
            How infrastructure projects — power plants, toll roads, LNG
            terminals, and more — are funded through non-recourse debt
            structures, SPVs, and multi-party risk allocation frameworks.
          </p>
        </div>
      </div>

      {/* ── Article body ─────────────────────────────────── */}
      <div style={{ backgroundColor: "#ffffff", padding: "4rem 0 5rem" }}>
        <div className="container-blog">
          <div style={{ display: "grid", gap: "0" }} className="md:grid-cols-[1fr_280px]">

            {/* Main content */}
            <article style={{ maxWidth: "72ch" }}>
              {SECTIONS.map((section, i) => (
                <section
                  key={i}
                  style={{
                    borderTop: i === 0 ? "3px solid #121212" : "1px solid #dfdfdf",
                    paddingTop: "2rem",
                    paddingBottom: "2rem",
                  }}
                >
                  <h2
                    style={{
                      fontFamily: SERIF,
                      fontSize: "clamp(1.25rem, 2.5vw, 1.5rem)",
                      fontWeight: 700,
                      color: "#121212",
                      lineHeight: 1.2,
                      marginBottom: "1rem",
                      letterSpacing: "-0.01em",
                    }}
                  >
                    {section.heading}
                  </h2>
                  {section.body.split("\n\n").map((para, j) => (
                    <p
                      key={j}
                      style={{
                        fontFamily: BODY,
                        fontSize: "1.0625rem",
                        color: "#333333",
                        lineHeight: 1.75,
                        marginBottom: j < section.body.split("\n\n").length - 1 ? "1rem" : 0,
                      }}
                    >
                      {para}
                    </p>
                  ))}
                </section>
              ))}
            </article>

            {/* Sidebar */}
            <aside
              style={{ paddingLeft: "3rem", paddingTop: "2rem" }}
              className="hidden md:block"
            >
              <div
                style={{
                  position: "sticky",
                  top: "80px",
                  display: "flex",
                  flexDirection: "column",
                  gap: "2rem",
                }}
              >
                {/* Contents */}
                <div style={{ borderTop: "3px solid #121212", paddingTop: "1.25rem" }}>
                  <p
                    style={{
                      fontFamily: SANS,
                      fontSize: "0.625rem",
                      fontWeight: 700,
                      letterSpacing: "0.14em",
                      textTransform: "uppercase",
                      color: "#888",
                      marginBottom: "0.875rem",
                    }}
                  >
                    In This Guide
                  </p>
                  <div style={{ display: "flex", flexDirection: "column", gap: "0" }}>
                    {SECTIONS.map((s, i) => (
                      <p
                        key={i}
                        style={{
                          fontFamily: SANS,
                          fontSize: "0.8125rem",
                          color: "#555",
                          lineHeight: 1.5,
                          padding: "0.5rem 0",
                          borderBottom: "1px solid #f0f0f0",
                        }}
                      >
                        {s.heading}
                      </p>
                    ))}
                  </div>
                </div>

                {/* Also see */}
                <div style={{ borderTop: "3px solid #121212", paddingTop: "1.25rem" }}>
                  <p
                    style={{
                      fontFamily: SANS,
                      fontSize: "0.625rem",
                      fontWeight: 700,
                      letterSpacing: "0.14em",
                      textTransform: "uppercase",
                      color: "#888",
                      marginBottom: "0.875rem",
                    }}
                  >
                    Also In Project Finance
                  </p>
                  <Link
                    href="/project-finance/private-equity"
                    style={{
                      display: "block",
                      fontFamily: SERIF,
                      fontSize: "0.9375rem",
                      fontWeight: 700,
                      color: "#121212",
                      textDecoration: "none",
                      lineHeight: 1.3,
                      marginBottom: "0.375rem",
                    }}
                    className="hover:text-gray-600"
                  >
                    Private Equity →
                  </Link>
                  <p
                    style={{
                      fontFamily: BODY,
                      fontSize: "0.875rem",
                      fontStyle: "italic",
                      color: "#888",
                      lineHeight: 1.55,
                    }}
                  >
                    Fund structures, LBO mechanics, value creation, and exit strategies explained.
                  </p>
                </div>
              </div>
            </aside>
          </div>
        </div>
      </div>
    </>
  );
}
